name: flutter1
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.6.0
  webview_flutter: ^4.7.0
  carousel_slider: ^4.2.1
  url_launcher : ^6.2.5
  image_picker: ^1.0.7
  firebase_core: ^2.27.2
  firebase_database: ^10.4.11
  firebase_storage: ^11.7.2
  cloud_firestore: ^4.15.10
  firebase_auth: ^4.18.0
  flutter_countdown_timer: ^4.1.0
  timezone: ^0.9.2
  uuid: ^4.4.0
  flutter_local_notifications: ^17.1.2
  awesome_notifications: ^0.9.3+1
  fl_chart: ^0.68.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  geolocator: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: false
  image_path: "assets/zoonegaralogo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logozooflutter.png
    - assets/images/background.jpg
    - assets/images/restinghut.png
    - assets/images/restinghut2.png
    - assets/images/openhour.png
    - assets/images/entrancezoo.jpg
    - assets/images/entrancefee.png
    - assets/images/tramstation.png
    - assets/images/tramstation2.png
    - assets/images/zoomap2.jpg
    - assets/images/panda.jpeg
    - assets/images/animalshow.jpg
    - assets/images/splashscreen.png
    - assets/images/alt_camera.png
    - assets/images/editinfo.jpg

    - assets/icons/panda.png
    - assets/icons/ape.png
    - assets/icons/buffalo.png
    - assets/icons/deer.png
    - assets/icons/stork.png
    - assets/icons/restinghut.png
    - assets/icons/food.png
    - assets/icons/toilet.png
    - assets/icons/tram.png
    - assets/icons/exhibiticon.png
    - assets/icons/remindericon.png
    - assets/zoonegaralogo.png

    - assets/icons/animals/bear.png
    - assets/icons/animals/giraffe.png
    - assets/icons/animals/kancil.png
    - assets/icons/animals/orangutan.png
    - assets/icons/animals/panther.png
    - assets/icons/animals/zebra.png
    - assets/icons/animals/visitedbear.png
    - assets/icons/animals/visitedgiraffe.png
    - assets/icons/animals/visitedkancil.png
    - assets/icons/animals/visitedorangutan.png
    - assets/icons/animals/visitedpanther.png
    - assets/icons/animals/visitedzebra.png

    - assets/icons/exhibits/apecentre.png
    - assets/icons/exhibits/bearcomplex.png
    - assets/icons/exhibits/mammal.png
    - assets/icons/exhibits/savannah.png
    - assets/icons/exhibits/visitedapecentre.png
    - assets/icons/exhibits/visitedbearcomplex.png
    - assets/icons/exhibits/visitedmammal.png
    - assets/icons/exhibits/visitedsavannah.png

    - assets/icons/facilities/food.png
    - assets/icons/facilities/restinghut.png
    - assets/icons/facilities/surau.png
    - assets/icons/facilities/toilet.png
    - assets/icons/facilities/tram.png

    - assets/maptheme/retro_theme.json
    
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
   - family: Bobby Jones
     fonts:
       - asset: assets/fonts/Bobby Rough Soft.ttf
         #style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
